// <auto-generated />
using System;
using Helpdesk.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Helpdesk.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Helpdesk.Core.Entities.Draft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("drafts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000001"),
                            Body = "Hi Priya,\n\nSorry for the trouble signing in. Let's get you back in:\n1) Use the \"Forgot password\" link and make sure you open the reset email within 30 minutes.\n2) Clear your browser cache or try an incognito window.\nIf it still fails, reply here and we'll reset it manually.\n\nBest,\nSupport",
                            CreatedAt = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsAiGenerated = true,
                            TicketId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1000000-0000-0000-0000-000000000002"),
                            Body = "Hi Sam,\n\nThanks for flagging this. I can see two charges for your monthly plan and have queued a refund for the duplicate — it should appear in 5–7 business days. You won't be charged twice going forward.\n\nBest,\nSupport",
                            CreatedAt = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsAiGenerated = true,
                            TicketId = new Guid("b1000000-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Helpdesk.Core.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("SenderName")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ThreadId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasFilter("\"MessageId\" IS NOT NULL");

                    b.HasIndex("State");

                    b.ToTable("tickets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000001"),
                            Body = "Hi, I've tried resetting my password twice but I still get an \"invalid credentials\" error when I sign in. Can you help? — Priya",
                            Category = "AccountLogin",
                            CreatedAt = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            MessageId = "msg-0001",
                            SenderEmail = "priya.student@example.edu",
                            SenderName = "Priya Student",
                            State = "NeedsReview",
                            Subject = "Can't log in to my account",
                            Summary = "Student cannot sign in; password reset did not resolve an invalid-credentials error.",
                            ThreadId = "thread-0001",
                            UpdatedAt = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000002"),
                            Body = "I see two charges for the monthly plan on my card statement. Could you check and refund the duplicate if it's a mistake? Thanks, Sam",
                            Category = "Billing",
                            CreatedAt = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            MessageId = "msg-0002",
                            SenderEmail = "sam.buyer@example.com",
                            SenderName = "Sam Buyer",
                            State = "NeedsReview",
                            Subject = "Was I charged twice this month?",
                            Summary = "Customer reports a possible duplicate monthly charge and requests a refund of the duplicate.",
                            ThreadId = "thread-0002",
                            UpdatedAt = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000003"),
                            Body = "The course videos just show a black screen in Safari but work fine in Chrome. Is there a fix? — Lee",
                            CreatedAt = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            MessageId = "msg-0003",
                            SenderEmail = "lee.learner@example.edu",
                            SenderName = "Lee Learner",
                            State = "NeedsReview",
                            Subject = "Video lectures won't play on Safari",
                            ThreadId = "thread-0003",
                            UpdatedAt = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Helpdesk.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Harshit Agarwal",
                            Email = "harshit.agarwal.se@gmail.com",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Helpdesk.Core.Entities.Draft", b =>
                {
                    b.HasOne("Helpdesk.Core.Entities.Ticket", "Ticket")
                        .WithOne("Draft")
                        .HasForeignKey("Helpdesk.Core.Entities.Draft", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Helpdesk.Core.Entities.Ticket", b =>
                {
                    b.Navigation("Draft");
                });
#pragma warning restore 612, 618
        }
    }
}
